loongson-community/areweloongyet

src/data/07-distros/slackware.yml
=> Update repo URL for slackware-loongarch64

blog/2023-06-27-these-weeks-in-loongarch-6.md
It's too early to consider it "progress" according to feedback.
=> Remove distro news from these-weeks-in-loongarch-6

docs/loong-or-loongarch.md
=> fix(docs): fix the Rust target tuple

blog/2023-07-24-test-rss.md, newsletter/2023-07-24-test-rss.md
Reverts loongson-community/areweloongyet#44
=> Revert "Revert "Test RSS feeds""

blog/2023-07-24-test-rss.md, newsletter/2023-07-24-test-rss.md
Reverts loongson-community/areweloongyet#45
套娃快乐
=> Revert "Revert "Revert "Test RSS feeds"""

docs/intro.md, docs/linux-upstream-support.md
=> docs: add linux upstream suppport status

docs/linux-upstream-support.md
=> docs: dedup linux-upstream-support.md a little bit

docs/old-and-new-worlds.md
=> doc/old-and-new-world: update new-world distro collection

docs/old-and-new-worlds.md
=> docs/old-and-new-worlds: fix link to Yongbao

docs/old-and-new-worlds.md
This would make sense since AreWeLoongYet? is in Chinese.
=> docs/old-and-new-worlds: use AOSC's zh_CN homepage

docs/collection-of-typical-configurations.md
Data is collected from AOSC Buildbot Stomatopoda.
=> docs: collection-of-typical-configurations: add 3c5000

docs/collection-of-typical-configurations.md
Data is collected from THTF L860-T2 Laptop (L71)
=> docs: collection-of-typical-configurations: add 3a5000m

docusaurus.config.ts, package.json, src/css/custom.css, yarn.lock
=> Search support

newsletter/2024-01-01-this-week-in-loongarch-31.md
Update the patch URL to v3.  And I really don't know how to properly fix MIPS :(.
=> twil-31: Fix some trivia about dirty fcsr issue

newsletter/2024-01-24-these-weeks-in-loongarch-33.md
=> docs(newsletter): these-weeks-in-loongarch-33: cover a missing llvm pr

src/data/02-programming-languages/fibjs.yml, src/data/porters.yml
=> feat(data): add fibjs

docs/world-compat-details/index.md
most importantly the major thinko involving the openAnolis *BPI* compatibility patch is fixed, among multiple other tweaks
=> docs: world-compat-details: more edits

src/components/HomepageFeatures/styles.module.css
=> css: Increase the gray depth of "good since" on the homepage

src/data/07-distros/deepin.yml
=> deepin 23 released

package.json, src/components/AsmDB/index.tsx, src/components/HomepageFeatures/index.tsx, src/plugins/awly-asmdb-plugin/index.ts, yarn.lock
And drive-by homepage rendering warning fixes
=> Fix asmdb routing (take 2)

newsletter/2023-07-24-this-week-in-loongarch-10.mdx, newsletter/2023-07-31-this-week-in-loongarch-11.md, newsletter/2023-09-04-this-week-in-loongarch-14.mdx, newsletter/2023-10-02-this-week-in-loongarch-18.mdx, newsletter/2023-10-16-this-week-in-loongarch-20.mdx, newsletter/2023-11-06-this-week-in-loongarch-23.mdx, newsletter/2023-11-13-this-week-in-loongarch-24.md, newsletter/2023-11-20-this-week-in-loongarch-25.mdx, newsletter/2023-12-05-this-week-in-loongarch-27/index.md
See: https://github.com/facebook/docusaurus/issues/9808
=> fix "broken link anchors" warnings

src/data/07-distros/alpine.yml
See https://alpinelinux.org/posts/Alpine-3.21.0-released.html
=> Add Alpine Linux to list of distros

docusaurus.config.ts, package.json, src/components/AsmDB/inputMinifloat.tsx, src/data/06-jit-runtimes/dotnet.yml, yarn.lock
See: https://dotnetconf.cn/2024
=> .NET Conf China 2024 updates

i18n/en/docusaurus-plugin-content-docs/current/baseline-reference.md, i18n/en/docusaurus-plugin-content-docs/current/collection-of-typical-configurations.md, i18n/en/docusaurus-plugin-content-docs/current/errata.md, i18n/en/docusaurus-plugin-content-docs/current/intro.md, i18n/en/docusaurus-plugin-content-docs/current/linux-upstream-support.md, i18n/en/docusaurus-plugin-content-docs/current/loong-or-loongarch.md, i18n/en/docusaurus-plugin-content-docs/current/old-and-new-worlds.md, i18n/en/docusaurus-plugin-content-docs/current/world-compat-details/index.md
=> feat: add locale en

src/data/07-distros/openwrt.yml
See https://lwn.net/ml/all/607e9b10-1b06-4e68-9be8-1f2d26d5ef24@hauke-m.de/
=> chore(data): mark OpenWrt as released since 24.10

src/components/AsmDB/encodingSpaceOverviewPage.tsx
This can be really handy for toolchain developers who need to tinker with raw instruction words.
Closes: #311
=> feat(asmdb): show insn opcode and mask

docs/loong-or-loongarch.md
Add new distros and programming languages to `loong-or-loongarch.md`.
=> docs/loong-or-loongarch.md: add new distros and languages

src/data/07-distros/loongfire.yml
updates loongfire github repo and download urls, changes descriptions to emphasize eBPF.
=> loongfire: update loongfire urls and description
